// output/qwik/src/components/MyComponent.jsx
import { Fragment, component$, h, useStore } from "@builder.io/qwik";

export const MyComponent = component$((props) => {
  const state = useStore({
    numbers: [1, 2, 3, 4, 5],
    vowels: ["a", "e", "i", "o", "u"],
  });

  return (
    <div>
      {state.numbers && state.numbers.length
        ? (state.numbers || []).map(function (number) {
            return <h1>number : {number}</h1>;
          })
        : null}
    </div>
  );
});

export default MyComponent;

// output/react/src/components/MyComponent.jsx
import * as React from "react";
import { useState } from "react";

function MyComponent(props) {
  const [numbers, setNumbers] = useState(() => [1, 2, 3, 4, 5]);

  const [vowels, setVowels] = useState(() => ["a", "e", "i", "o", "u"]);

  return (
    <div>
      {numbers && numbers.length ? (
        <>
          {numbers?.map((number) => (
            <h1>number :{number}</h1>
          ))}
        </>
      ) : null}
    </div>
  );
}

export default MyComponent;
