// output/react/src/components/widgets/Accordion/accordion.jsx
import * as React from "react";
import { useState } from "react";
import AccordionItem from "./accordion-item";

function Accordion(props) {
  const [open, setOpen] = useState(() => []);

  const [onlyOneAtATime, setOnlyOneAtATime] = useState(() =>
    Boolean(props.grid || props.oneAtATime)
  );

  const [getOpenGridItemPosition, setGetOpenGridItemPosition] = useState(
    () => props.grid && open.length
  );

  const [openGridItemOrder, setOpenGridItemOrder] = useState(() => null);

  return (
    <>
      <div className="builder-accordion div">
        {props.items ? (
          <>
            {props.items?.map((item, index) => (
              <AccordionItem
                state={state}
                titleBlocks={item.title}
                detailBlocks={item.detail}
                index={index}
                openGridItemOrder={openGridItemOrder}
                onlyOneAtATime={(event) => onlyOneAtATime}
              />
            ))}
          </>
        ) : null}
      </div>
      <style jsx>{`
        .div {
          display: flex;
          align-items: stretch;
          flex-direction: column;
        }
      `}</style>
    </>
  );
}

export default Accordion;

// output/qwik/src/components/widgets/Accordion/accordion.jsx
import AccordionItem from "./accordion-item";

import {
  Fragment,
  component$,
  h,
  useStore,
  useStylesScoped$,
} from "@builder.io/qwik";

export const Accordion = component$((props) => {
  useStylesScoped$(STYLES);

  const state = useStore({
    getOpenGridItemPosition: props.grid && open.length,
    onlyOneAtATime: Boolean(props.grid || props.oneAtATime),
    open: [],
    openGridItemOrder: null,
  });

  return (
    <div class="builder-accordion div-Accordion">
      {props.items
        ? (props.items || []).map(function (item, index) {
            return (
              <AccordionItem
                state={state}
                titleBlocks={item.title}
                detailBlocks={item.detail}
                index={index}
                openGridItemOrder={state.openGridItemOrder}
                onlyOneAtATime={state.onlyOneAtATime}
              ></AccordionItem>
            );
          })
        : null}
    </div>
  );
});

export default Accordion;

export const STYLES = `
.div-Accordion {
  display: flex;
  align-items: stretch;
  flex-direction: column;
}
`;
